# Generated by Django 3.2.12 on 2024-04-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akarat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biens_immobiliers',
            name='lien',
        ),
        migrations.AddField(
            model_name='biens_immobiliers',
            name='adresse',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='biens_immobiliers',
            name='categorie',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='biens_immobiliers',
            name='emplacement',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='biens_immobiliers',
            name='region',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='biens_immobiliers',
            name='prix',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='biens_immobiliers',
            name='surface',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='biens_immobiliers',
            name='type_de_bien',
            field=models.CharField(max_length=50),
        ),
    ]
